# Generated by Django 3.0.7 on 2022-02-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buhi_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='created_at',
            new_name='created_on',
        ),
    ]
